# 设置 MySQL 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epidemic?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 设置国际化
  messages:
    basename: i18n.list

# 发送邮件
  mail:
    host: smtp.qq.com
    username: 847818218@qq.com
    password: tbolyqdizctwbaij
    propertie.mail.smtp.ssl.enable: true


